travis:
  secure:
    BINSTAR_TOKEN: cL0Jvz4iB6Da4Bwarg5swDAlDCnsHGyRUFZSSgd5fbV9AaVaOTofGUDfvBIO8LzpxVE/xdCslNB/9Dl6FhnlzJdAeD0YpKC5faMFPvZ2FjDQ1LfVRDNjYO/FBW5v3TOcZysWlIFf+/OEY3kO5RRaV6VlDPqxRp7jk8nzc+cOAknxHfzoixMVmSADNTYYe8IXk7PKb/rO7J00azGoZVJtlC+QpWenUK7O2AgsXveje16JtlIfBY/49zJYA64gTunpHirpGjwI2GfMbuyHMcyqJ6MufJNUSd3m3O7bT7+QxEvYydAgpascga06SozCYnBch5/vpk1iLJv4Jc5sJOTrGU6muk0ClXVsnb0QCgjWFBsAWKIZeAeYugublRBIQntLDVAtQLZTAaw4SI9M/MhKa0oGf/yxsSJb58Qnr9MbK8fQD8G+hOAs6/XiB/tmqDtjvUlsdydqCzo+U7zxj/nQc6MgYlhXs5eMHx7l/mUZeuYZSGhXAUOEF4Fpmvp1lePhcYUCwQgTZH8UXIuO5TAliYENpJwycC0PvilSaEkNEqWH3zCKPEJKHq7qgyzwuaBJGYc0mvAlW37kG3Hs0zVsIiB/D0iYYOSssxivktSe6uGDJ9A4zEfZrL41EUG3yMhXZLnkBgmUn0no2saO1XRyJoFrkLJq8TMaZmxdS1N96mo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
